global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/793c38e3-6348-45db-a8c8-923a69d12a4a'
          send_resolved: false