global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - '192.168.2.117:9090:9094'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.2.117:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['192.168.2.117:9100']

  - job_name: simple_server
    static_configs:
      - targets: ["192.168.2.117:8090"]

  - job_name: grafana
    static_configs:
      - targets: ["192.168.2.117:3000"]
  
